apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabel:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
